### ISSUE TITLE
function-sample-azure doesn't work locally.

### ISSUE THREAD

**Issue by sandeepmaurya** [spring-cloud/spring-cloud-function#384] opened 2019-07-04 08:47 UTC
Please see attached BeforeVersionChange.txt for the error that I get when I run the sample as is.

Then I changed host.json to 
{
	"version":"2.0",
	"functionTimeout": "00:10:00"
}

This time the function started ok but gives runtime errors. Please see AfterVersionChange.txt.
[AfterVersionChange.txt](https://github.com/spring-cloud/spring-cloud-function/files/3358451/AfterVersionChange.txt)
[BeforeVersionChange.txt](https://github.com/spring-cloud/spring-cloud-function/files/3358452/BeforeVersionChange.txt)

**Comment by sandeepmaurya** [comment] 2019-07-05 09:15
These links helped me make some progress.
https://github.com/Azure/azure-functions-java-worker/issues/255
https://stackoverflow.com/questions/55621375/azure-function-with-spring-boot-spring-cloud-function-unable-to-locate-main-cl

Changes:

### host.json
{
  "version": "2.0"
}

### pom.xml
			<dependency>
				<groupId>org.springframework.cloud</groupId>
				<artifactId>spring-cloud-function-dependencies</artifactId>
				<version>2.0.1.RELEASE</version>
				<type>pom</type>
				<scope>import</scope>
			</dependency>


### FooHandler.java
	@FunctionName("uppercase")
	public Bar execute(

			@HttpTrigger(name = "req", methods = { HttpMethod.GET,
					HttpMethod.POST }, authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<Foo>> request,
			ExecutionContext context) {
		Optional<Foo> body = request.getBody();
		Foo foo = body.get();
		return handleRequest(foo, context);
	}

**Comment by olegz** [comment] 2019-09-04 16:48
@sandeepmaurya I am not sure i follow. Looking at your stack traces I don't see a single stack frame pointing to spring-cloud-function. Can you please clarify?

**Comment by aropop** [comment] 2019-10-03 12:16
@olegz I seem to have a similar issue. When you have an azure function as follows: 
`    @FunctionName("foo-bar")
    public List<Bar> execute(@HttpTrigger(name = "req",
            methods = {HttpMethod.POST},
            authLevel = AuthorizationLevel.ANONYMOUS) HttpRequestMessage<Optional<Foo>> request,
            ExecutionContext context) {
        return handleRequest(request.getBody(), context);
    }`

It will actually never fill the Optional with a value since in spring-cloud-function-web RequestProcessor, the request body will be mapped to Optional. 

Instead I think it should be mapped onto the Foo class if possible else Optional.empty should be returned.

**Comment by olegz** [comment] 2019-12-12 19:19
The example has been fixed, validated and tested both locally and in Azure platform. Some  dependencies were upgraded and some fixes were applied. You can see more here - https://github.com/spring-cloud/spring-cloud-function/commit/0f38ea47b8a3f3665111cfa04c7e5dc028437828

So I'll close this for now but feel free to reopen if you believe the issue is still there

**Closed by olegz** 2019-12-12 19:19 UTC
Labels: waiting-on-feedback
