### ISSUE TITLE
Error when try the example function-sample-gcp-background when using Google PubSub emulator

### ISSUE THREAD

**Issue by ptschi** [spring-cloud/spring-cloud-function#851] opened 2022-04-07 12:47 UTC
I have to try implement the example [function-sample-gcp-background](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-gcp-background)
I have install the Google [Pubsub emulator ](https://cloud.google.com/pubsub/docs/emulator) from Google SDK 380.0.0  on my pc (windows 10 20H2)
Then I create topic and push subcription to my function (http://localhost:8080/)
When I publish message using python script provided by Google or using java programe using google Publisher (com.google.cloud.pubsub.v1.Publisher)  

- I have a exception:

` AVERTISSEMENT: Failed to execute org.springframework.cloud.function.adapter.gcp.GcfJarLauncher
java.lang.NullPointerException: Cannot invoke "java.lang.String.getBytes(java.nio.charset.Charset)" because "src" is null
	at java.base/java.util.Base64$Decoder.decode(Base64.java:589)
	at com.example.CloudFunctionMain.lambda$pubSubFunction$0(CloudFunctionMain.java:29)
	at com.example.CloudFunctionMain$$Lambda$531/0x000000007322ca70.accept(Unknown Source)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.invokeConsumer(SimpleFunctionRegistry.java:972)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.doApply(SimpleFunctionRegistry.java:698)
	at org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry$FunctionInvocationWrapper.apply(SimpleFunctionRegistry.java:544)
	at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.service(FunctionInvoker.java:98)
	at org.springframework.cloud.function.adapter.gcp.GcfJarLauncher.service(GcfJarLauncher.java:53)
	at com.google.cloud.functions.invoker.NewHttpFunctionExecutor.service(NewHttpFunctionExecutor.java:65)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:755)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:547)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:233)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1297)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:188)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:485)
	at org.eclipse.jetty.server.handler.ScopedHandler.nextScope(ScopedHandler.java:186)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1212)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at com.google.cloud.functions.invoker.runner.Invoker$NotFoundHandler.handle(Invoker.java:397)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:127)
	at org.eclipse.jetty.server.Server.handle(Server.java:500)
	at org.eclipse.jetty.server.HttpChannel.lambda$handle$1(HttpChannel.java:383)
	at org.eclipse.jetty.server.HttpChannel$$Lambda$637/0x0000000073400840.dispatch(Unknown Source)
	at org.eclipse.jetty.server.HttpChannel.dispatch(HttpChannel.java:547)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:375)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:270)
	at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:311)
	at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:103)
	at org.eclipse.jetty.io.ChannelEndPoint$2.run(ChannelEndPoint.java:117)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:336)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:313)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:171)
	at org.eclipse.jetty.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:129)
	at org.eclipse.jetty.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:388)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:806)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$Runner.run(QueuedThreadPool.java:938)
	at java.base/java.lang.Thread.run(Thread.java:884)
 `

- It's working fine, I use a curl command from POSTMAN or from Git bash. 
`curl localhost:8080 -H "Content-Type: application/json" -d '{"data":"aGVsbG8="}' `

I have also try to run GCP emulator from Docker for windows and I have the same exception.

If I publish the message to the emulator to a java client not using Spring framework it's working fine with this code
`@Slf4j
public class Function implements BackgroundFunction<PubSubMessage> {
  // This is the Pub/Sub message format from the Pub/Sub emulator.
  @Override
  public void accept(PubSubMessage pubSubMessage, Context context) {

    log.info("Received message with id " + context.eventId());
    String message = null;
    if (pubSubMessage != null && pubSubMessage.getData() != null) {
      message =
          new String(
              Base64.getDecoder().decode(pubSubMessage.getData().getBytes(StandardCharsets.UTF_8)),
              StandardCharsets.UTF_8);
    }
    return;
  }
}`

Thank you for your consideration

**Comment by elefeint** [comment] 2022-04-07 13:39
@ptschi Thank you for the report!
@ddixit14 Could you try to reproduce this?

**Comment by ptschi** [comment] 2022-04-07 14:16
FYI, I have reproduce the issue on another pc with fresh windows 11 installation
Step to reproduce, on a windows machine: 
- clone the example of[ spring cloud backgroud function ](https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-gcp-background)
- install [google sdk](https://dl.google.com/dl/cloudsdk/channels/rapid/GoogleCloudSDKInstaller.exe) & pubsub emulator
- Follow google [guidelines ](https://cloud.google.com/pubsub/docs/emulator)to use emulator (set env variables, get python exemple..)
- create a topic and push subcription to cloud function endpoint 
- Start cloud function using mvn function:run
- publish message usign python utils

I have tested  using 
- IntelliJ IDEA 2021.3.3 (
- maven apache-maven-3.8.5
- IBM Semeru jdk-17.0.2+8
- Google pubsub emulator 0.60.0
- Win 11 21H2 & win 10 20H2

**Comment by elefeint** [comment] 2022-04-07 19:33
@ptschi It looks like we'll have to revisit the local function invocation after the adapter is upgraded to the latest version of GCF. As originally written, only [local testing over HTTP was supported](https://docs.spring.io/spring-cloud-function/docs/3.2.3/reference/html/gcp.html#_getting_started_2), and testing over Pub/Sub was not intended.

We will leave the issue open to track the work.

**Comment by ptschi** [comment] 2022-04-08 09:07
@elefeint, I have analysis the issue because my understanding the pubsub emulator is making a HTTP Post request to the local cloud function endpoint. So PubSub emulator is kind of local testing with HTTP.
I have check a local cloud function using google framework and function-maven-plugin, it's excepted to receive http request like
`curl --header "Content-Type: application/json" --request POST --data '{"data":{"message":"This is a message"}}' http://localhost:8080/`
The data are not base64 encoded.
With Spring Cloud function, the local Cloud function is excepted a request like
`curl localhost:8080 -H "Content-Type: application/json" -d '{"data":"aGVsbG8="}'`
With the data encode in base64, like may be, the real pubsub.

**Comment by ptschi** [comment] 2022-04-08 11:41
@elefeint, I have analysis the issue because my understanding the pubsub emulator is making a HTTP Post request to the local cloud function endpoint. So PubSub emulator is kind of local testing with HTTP.
I have check a local cloud function using google framework and function-maven-plugin, it's excepted to receive http request like
curl --header "Content-Type: application/json" --request POST --data '{"data":{"message":"This is a message"}}' http://localhost:8080/
The data are not base64 encoded.
With Spring Cloud function, the local Cloud function is excepted a request like
curl localhost:8080 -H "Content-Type: application/json" -d '{"data":"aGVsbG8="}'
With the data encode in base64, like may be, the real pubsub.

**Comment by elefeint** [comment] 2022-04-08 13:36
That's right. Testing Pub/Sub messages locally is not currently supported. Testing with HTTP directly is your best bet.

**Comment by olegz** [comment] 2022-04-21 11:23
@elefeint should we close this? Based on your comments it appears to be resolved

**Comment by elefeint** [comment] 2022-04-25 14:27
Yes, please -- this isn't expected to be supported.

**Closed** 2022-05-04 08:47 UTC
Labels: waiting-on-feedback, GCF
