### ISSUE TITLE
GCP http sample not working

### ISSUE THREAD

**Issue by Jojoooo1** [spring-cloud/spring-cloud-function#774] opened 2021-11-29 18:20 UTC
**Describe the bug**
After download the http sample function and followed spring cloud function docs to deploy :
```
gcloud functions deploy function-sample-gcp-http \
--entry-point org.springframework.cloud.function.adapter.gcp.GcfJarLauncher \
--runtime java11 \
--trigger-http \
--source target/deploy \
--memory 512MB \
```

Function is getting deploy with an errors:

Exception in thread "main" java.lang.RuntimeException: Could not construct an instance of org.springframework.cloud.function.adapter.gcp.GcfJarLauncher: java.lang.reflect.InvocationTargetException at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:57) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:243) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121) Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:53) ... 2 more Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at org.springframework.cloud.function.adapter.gcp.GcfJarLauncher.<init>(GcfJarLauncher.java:48) ... 7 more Caused by: java.lang.NoSuchMethodError: 'void org.springframework.cloud.function.context.FunctionalSpringApplication.setApplicationContextClass(java.lang.Class)' at org.springframework.cloud.function.context.FunctionalSpringApplication.<init>(FunctionalSpringApplication.java:66) at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.springApplication(AbstractSpringFunctionAdapterInitializer.java:378) at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:121) at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.init(FunctionInvoker.java:78) at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.<init>(FunctionInvoker.java:58) ... 12 more
Exception in thread "main" java.lang.RuntimeException: Could not construct an instance of org.springframework.cloud.function.adapter.gcp.GcfJarLauncher: java.lang.reflect.InvocationTargetException at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:57) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:243) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121) Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:53) ... 2 more Caused by: java.lang.reflect.InvocationTargetException at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490) at org.springframework.cloud.function.adapter.gcp.GcfJarLauncher.<init>(GcfJarLauncher.java:48) ... 7 more Caused by: java.lang.NoSuchMethodError: 'void org.springframework.cloud.function.context.FunctionalSpringApplication.setApplicationContextClass(java.lang.Class)' at org.springframework.cloud.function.context.FunctionalSpringApplication.<init>(FunctionalSpringApplication.java:66) at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.springApplication(AbstractSpringFunctionAdapterInitializer.java:378) at org.springframework.cloud.function.context.AbstractSpringFunctionAdapterInitializer.initialize(AbstractSpringFunctionAdapterInitializer.java:121) at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.init(FunctionInvoker.java:78) at org.springframework.cloud.function.adapter.gcp.FunctionInvoker.<init>(FunctionInvoker.java:58)

**Sample**
https://github.com/spring-cloud/spring-cloud-function/tree/main/spring-cloud-function-samples/function-sample-gcp-http

**Comment by elefeint** [comment] 2021-12-10 22:25
The problem is with `org.springframework.cloud:spring-cloud-function-adapter-gcp` version. 3.1.3-snapshot fails, but 3.1.4 and later work fine.
I'll update the sample.

**Comment by Jojoooo1** [comment] 2021-12-10 22:45
Tried with the latest value and was giving this errors:

```
"main" java.lang.RuntimeException: Class com.intelipoint.service.invoice.InvoiceApplication does not implement com.google.cloud.functions.HttpFunction at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:49) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:243) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121)
Exception in thread "main" java.lang.RuntimeException: Class com.intelipoint.service.invoice.InvoiceApplication does not implement com.google.cloud.functions.HttpFunction at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:49) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:243) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:121)
```

**Comment by elefeint** [comment] 2021-12-10 23:03
@Jojoooo1 Make sure to add a newline after the `Main-Class: package.ClassName` in your MANIFEST.MF.

**Comment by Jojoooo1** [comment] 2021-12-10 23:19
Yes it is set as defined in the docs in resources/META-INF/MANIFEST.MF

`
Main-Class: com.intelipoint.service.invoice.InvoiceApplication
`

**Comment by Jojoooo1** [comment] 2021-12-10 23:24
let me know if you had success doing the deploy. I tried in every possible way and had to re implement my fcn as pure java fcn.

**Comment by elefeint** [comment] 2021-12-11 03:26
Add a newline at the end. 
I was able to deploy to GCF after the changes in #782.

**Comment by elefeint** [comment] 2021-12-11 03:27
A faster way to test is locally, with `mvn function:run`

**Comment by Jojoooo1** [comment] 2021-12-11 09:24
Yes @elefeint  i had no problem testing locally, this is the deploy in GCP that is giving error.

**Comment by elefeint** [comment] 2021-12-14 00:18
@Jojoooo1 We've had two people successfully deploy to GCF from `main` branch of `function-sample-gcp-http` sample. 
Could you make sure that:
1) you are doing `mvn clean` before attempting to package.
2) you are on the latest version of `main` branch.
3) there are no local differences

**Comment by olegz** [comment] 2022-03-08 14:17
Closing based on the request from @elefeint as the problem seem to be addressed

**Closed by olegz** 2022-03-08 14:17 UTC
Labels: GCF
