### ISSUE TITLE
AWS Lambda initializing twice

### ISSUE THREAD

**Issue by dfeingol** [spring-cloud/spring-cloud-function#1048] opened 2023-06-12 03:03 UTC
**My spring cloud function deployed correctly in AWS but it was called multiple times by the org.springframework.cloud.function.adapter.aws.FunctionInvoker not sure why. I am using "3.2.8" of Spring cloud functions and using JDK11 because that was the highest version that AWS supported when the project started. Below is the init sequence:**
```
**2023-06-11T20:19:56.492-04:00	2023-06-12 00:19:56 INFO [main] o.s.c.f.u.FunctionClassUtils Loaded Start Class: class com.softintegration.ApplicationStarter**

**2023-06-11T20:19:56.492-04:00	2023-06-12 00:19:56 INFO [main] o.s.c.f.u.FunctionClassUtils Main class: class com.softintegration.ApplicationStarter**

2023-06-11T20:19:58.032-04:00	. ____ _ __ _ _
2023-06-11T20:19:58.032-04:00	/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
2023-06-11T20:19:58.032-04:00	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2023-06-11T20:19:58.032-04:00	\\/ ___)| |_)| | | | | || (_| | ) ) ) )
2023-06-11T20:19:58.048-04:00	' |____| .__|_| |_|_| |_\__, | / / / /
2023-06-11T20:19:58.048-04:00	=========|_|==============|___/=/_/_/_/

2023-06-11T20:19:58.052-04:00	:: Spring Boot :: (v2.7.7)

2023-06-11T20:19:58.315-04:00	2023-06-12 00:19:58 INFO [background-preinit] o.h.v.i.u.Version HV000001: Hibernate Validator null

2023-06-11T20:19:58.371-04:00	2023-06-12 00:19:58 INFO [main] o.s.c.f.a.a.CustomRuntimeInitializer AWS Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker

2023-06-11T20:19:58.393-04:00	2023-06-12 00:19:58 INFO [main] l.AWSLambda Starting AWSLambda using Java 11.0.19 on 169.254.42.109 with PID 8 (/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar started by sbx_user1051 in /var/task)

2023-06-11T20:19:58.394-04:00	2023-06-12 00:19:58 INFO [main] l.AWSLambda The following 1 profile is active: "dev"

2023-06-11T20:20:00.910-04:00	2023-06-12 00:20:00 INFO [main] o.s.d.r.c.RepositoryConfigurationDelegate Bootstrapping Spring Data JDBC repositories in DEFAULT mode.

2023-06-11T20:20:00.952-04:00	2023-06-12 00:20:00 INFO [main] o.s.d.r.c.RepositoryConfigurationDelegate Finished Spring Data repository scanning in 34 ms. Found 0 JDBC repository interfaces.

2023-06-11T20:20:04.072-04:00	2023-06-12 00:20:04 INFO [main] o.f.c.ApplicationStarter In application starter

2023-06-11T20:20:04.075-04:00	2023-06-12 00:20:04 INFO [main] o.f.c.ApplicationStarter Setting up the database

2023-06-11T20:20:04.075-04:00	2023-06-12 00:20:04 INFO [main] o.f.c.ApplicationStarter finished accessing the database

2023-06-11T20:20:05.705-04:00	Picked up JAVA_TOOL_OPTIONS: -Dspring.profiles.active=dev

2023-06-11T20:20:06.991-04:00	2023-06-12 00:20:06 INFO [main] o.s.c.f.u.FunctionClassUtils Searching for start class in manifest: jar:file:/var/runtime/lib/aws-lambda-java-core-1.2.2.jar!/META-INF/MANIFEST.MF

2023-06-11T20:20:06.991-04:00	Manifest-Version: 1.0

2023-06-11T20:20:06.991-04:00	Archiver-Version: Plexus Archiver

2023-06-11T20:20:06.991-04:00	Created-By: Apache Maven

2023-06-11T20:20:06.991-04:00	Built-By: andclt

2023-06-11T20:20:06.991-04:00	Build-Jdk: 1.8.0_342

2023-06-11T20:20:06.995-04:00	2023-06-12 00:20:06 INFO [main] o.s.c.f.u.FunctionClassUtils Searching for start class in manifest: jar:file:/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar!/META-INF/MANIFEST.MF

2023-06-11T20:20:06.995-04:00	Manifest-Version: 1.0

2023-06-11T20:20:06.995-04:00	Archiver-Version: Plexus Archiver

2023-06-11T20:20:06.995-04:00	Created-By: Apache Maven 3.6.3

2023-06-11T20:20:06.995-04:00	Built-By: root

2023-06-11T20:20:06.995-04:00	Build-Jdk: 11.0.18

2023-06-11T20:20:06.996-04:00	2023-06-12 00:20:06 INFO [main] o.s.c.f.u.FunctionClassUtils Searching for start class in manifest: jar:file:/var/runtime/lib/aws-lambda-java-serialization-0.2.0.jar!/META-INF/MANIFEST.MF

2023-06-11T20:20:06.996-04:00	Manifest-Version: 1.0

2023-06-11T20:20:06.996-04:00	Archiver-Version: Plexus Archiver

2023-06-11T20:20:06.996-04:00	Created-By: Apache Maven 3.6.3

2023-06-11T20:20:06.996-04:00	Built-By: root

2023-06-11T20:20:06.996-04:00	Build-Jdk: 11.0.18

2023-06-11T20:20:06.996-04:00	2023-06-12 00:20:06 INFO [main] o.s.c.f.u.FunctionClassUtils Searching for start class in manifest: jar:file:/var/runtime/lib/org-crac-inmemory-0.1.0.jar!/META-INF/MANIFEST.MF

2023-06-11T20:20:06.997-04:00	Manifest-Version: 1.0

2023-06-11T20:20:06.997-04:00	Archiver-Version: Plexus Archiver

2023-06-11T20:20:06.997-04:00	Created-By: Apache Maven 3.6.3

2023-06-11T20:20:06.997-04:00	Built-By: root

2023-06-11T20:20:06.997-04:00	Build-Jdk: 11.0.18

2023-06-11T20:20:06.997-04:00	2023-06-12 00:20:06 INFO [main] o.s.c.f.u.FunctionClassUtils Searching for start class in manifest: jar:file:/var/runtime/amzn-log4j-security-jdk11-0.1alpha.jar!/META-INF/MANIFEST.MF

2023-06-11T20:20:06.997-04:00	Manifest-Version: 1.0

2023-06-11T20:20:06.997-04:00	Premain-Class: Log4jPatch

2023-06-11T20:20:06.998-04:00	Created-By: 11.0.13 (Amazon.com Inc.)

2023-06-11T20:20:06.999-04:00	2023-06-12 00:20:06 INFO [main] o.s.c.f.u.FunctionClassUtils Searching for start class in manifest: file:/var/task/META-INF/MANIFEST.MF

2023-06-11T20:20:06.999-04:00	Manifest-Version: 1.0

2023-06-11T20:20:06.999-04:00	Created-By: Maven Jar Plugin 3.2.0

2023-06-11T20:20:06.999-04:00	Build-Jdk-Spec: 11


**2023-06-11T20:20:07.132-04:00	2023-06-12 00:20:07 INFO [main] o.s.c.f.u.FunctionClassUtils Loaded Start Class: class com.softintegration.ApplicationStarter**

**2023-06-11T20:20:07.132-04:00	2023-06-12 00:20:07 INFO [main] o.s.c.f.u.FunctionClassUtils Main class: class com.softintegration.ApplicationStarter**

2023-06-11T20:20:09.730-04:00	. ____ _ __ _ _
2023-06-11T20:20:09.730-04:00	/\\ / ___'_ __ _ _(_)_ __ __ _ \ \ \ \
2023-06-11T20:20:09.730-04:00	( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
2023-06-11T20:20:09.730-04:00	\\/ ___)| |_)| | | | | || (_| | ) ) ) )
2023-06-11T20:20:09.730-04:00	' |____| .__|_| |_|_| |_\__, | / / / /
2023-06-11T20:20:09.730-04:00	=========|_|==============|___/=/_/_/_/

2023-06-11T20:20:09.751-04:00	:: Spring Boot :: (v2.7.7)

2023-06-11T20:20:10.131-04:00	2023-06-12 00:20:10 INFO [background-preinit] o.h.v.i.u.Version HV000001: Hibernate Validator null

2023-06-11T20:20:10.350-04:00	2023-06-12 00:20:10 INFO [main] o.s.c.f.a.a.CustomRuntimeInitializer AWS Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker

2023-06-11T20:20:10.410-04:00	2023-06-12 00:20:10 INFO [main] l.AWSLambda Starting AWSLambda using Java 11.0.19 on 169.254.42.109 with PID 8 (/var/runtime/lib/aws-lambda-java-runtime-0.2.0.jar started by sbx_user1051 in /var/task)

2023-06-11T20:20:10.411-04:00	2023-06-12 00:20:10 INFO [main] l.AWSLambda The following 1 profile is active: "dev"

2023-06-11T20:20:14.753-04:00	2023-06-12 00:20:14 INFO [main] o.s.d.r.c.RepositoryConfigurationDelegate Bootstrapping Spring Data JDBC repositories in DEFAULT mode.

2023-06-11T20:20:14.851-04:00	2023-06-12 00:20:14 INFO [main] o.s.d.r.c.RepositoryConfigurationDelegate Finished Spring Data repository scanning in 90 ms. Found 0 JDBC repository interfaces.


2023-06-11T20:20:20.717-04:00	2023-06-12 00:20:20 INFO [main] o.f.c.ApplicationStarter In application starter

2023-06-11T20:20:20.728-04:00	2023-06-12 00:20:20 INFO [main] o.f.c.ApplicationStarter Setting up the database

2023-06-11T20:20:20.728-04:00	2023-06-12 00:20:20 INFO [main] o.f.c.ApplicationStarter finished accessing the database
```

**Comment by olegz** [comment] 2023-07-13 15:51
Hmm, i need a way to reproduce it. Do you have a simple app that you can push to GutHub so we can look?

**Comment by olegz** [comment] 2023-09-26 04:38
Closing it due to lack of follow up from the user

**Closed by olegz** 2023-09-26 04:38 UTC
Labels: waiting-on-feedback, AWS
