### ISSUE TITLE
Zipkin Consistency + Support Log Tracing for AWS WebFlux Functions

### ISSUE THREAD

**Issue by davidmelia** [spring-cloud/spring-cloud-function#998] opened 2023-01-31 13:47 UTC
Hi,

This potentially is half bug + half feature request

In my super simple Spring Cloud 2022.0.1 AWS function example https://github.com/davidmelia/spring-cloud-function-zipkin/tree/function-webclient-tracing I want to be able to automatically log the trace IDs in the logs to use log trace tools such as splunk and use zipkin to diagnose issues.

My simple function accepts an AWS lambda payload and calls a http API.

**1) Zipkin Issue**

Out of the box we get two separate traces for one invocation which I think is wrong:

<img width="1034" alt="image" src="https://user-images.githubusercontent.com/8583712/215775019-ed1ba47e-26f4-48ae-8e74-a558fd72b132.png">

I would of expected a single trace id in this case.

**2) Logback Context Feature Request** 

When running my example we do not get any logback MDC context information

`[aid=spring-cloud-function-zipkin,tid=,sid=]`

even though I am using the described way to do this

```
  @Override
  public Flux<String> apply(Flux<Map<String, String>> flux) {
    return flux.flatMap(response -> {
      // tracer.startScopedSpan("dave");
      return Mono.deferContextual(contextView -> {
        try (ContextSnapshot.Scope scope = ContextSnapshot.setThreadLocalsFrom(contextView, ObservationThreadLocalAccessor.KEY)) {

          log.info("response is {}", response);
          return webClient.get().retrieve().bodyToMono(Map.class).map(r -> {
            log.info("response={}", r);
            return r;
          }).thenReturn("OK").delayElement(Duration.ofSeconds(4));
        }
      });
    });
  }
```
Is this possible to add automatically?

Thanks

**Comment by davidmelia** [comment] 2023-02-21 09:37
Hi, Further to the above I have attempted to switch to the new Hooks.enableAutomaticContextPropagation() way -see https://github.com/davidmelia/spring-cloud-function-zipkin/tree/function-webcllient-tracing-hooks 

```
  @Override
  public Flux<String> apply(Flux<Map<String, String>> flux) {
    return flux.flatMap(request -> {
      log.info("1) this does not have a trace id");
      return Mono.just(request).doOnNext(r -> log.info("2) this does not have a trace id", request)).then(webClient.get().retrieve().bodyToMono(Map.class).map(r -> {
        log.info("3) this does have a trace id");
        return r;
      }).thenReturn("OK"));

    }).tap(Micrometer.observation(observationRegistry));
  }
```
 results in

```
INFO [aid=spring-cloud-function-zipkin,tid=,sid=] 81212 --- [           main] example.WebClientFunction                : 1) this does not have a trace id
INFO [aid=spring-cloud-function-zipkin,tid=,sid=] 81212 --- [           main] example.WebClientFunction                : 2) this does not have a trace id
INFO [aid=spring-cloud-function-zipkin,tid=63f48f8fb88a00ac4346eb62afe98637,sid=4346eb62afe98637] 81212 --- [ctor-http-nio-2] example.WebClientFunction                : 3) this does have a trace id
```

_Note without .tap there is no tracing_

**Comment by olegz** [comment] 2023-02-28 15:31
What relevance does this have to s-c-function? We do not do anything related to tracing. 
Just trying to see if I am missing something.

**Comment by davidmelia** [comment] 2023-03-02 08:23
Ok so this isn't a bug but rather a feature request to see if spring cloud function can automatically start and stop a trace around the functional entry point. (Similar to spring boot webflux around the controller entry point)? 

It's super useful when using a product like zipkin to see traces from spring app types.

**Comment by olegz** [comment] 2023-03-03 11:30
The problem is that functions are rarely (never) used by themselves. For example in the case of s-c-stream you get tracing info based on the relevant code provided by the binders and frameworks they use (e.g., s-kafka, s-amqp). 
I am just wondering if that is going to create confusion with other frameowrks?

**Comment by davidmelia** [comment] 2023-04-13 14:35
@olegz this has been quite difficult to get trace IDs but https://github.com/davidmelia/spring-cloud-function-zipkin/tree/function-webcllient-tracing-hooks contains a working example.  The key here is 

```
  @Override
  public Flux<String> apply(Flux<Map<String, String>> flux) {
    return flux
        .contextWrite(context -> Context.empty())
        .....
        .tap(Micrometer.observation(observationRegistry))
        .contextCapture();        
```

This gives a new tid per event.

Spring Boot Webflux handles all of this automagically for http requests.  What are your thoughts about having first class support for trade IDs in spring cloud function? Could the above boiler plate be added to spring cloud function?

Thanks

**Comment by olegz** [comment] 2023-06-07 12:52
I have not thought about it and it is certainly not of highest priority. But I will be more then willing to review the PR if you are willing to take a pass at it

**Comment by olegz** [comment] 2023-09-25 14:58
I this this has been covered with https://github.com/spring-cloud/spring-cloud-stream/issues/2782. Plus usage of reactive functions in AWS would not make much sense since API Gateway request itself is blocking.

I'll close it as there us no forceable action on this.

**Closed by olegz** 2023-09-25 14:58 UTC
Labels: waiting-on-feedback
