### ISSUE TITLE
FunctionCatalog bean missing when run with Spring 3.x 

### ISSUE THREAD

**Issue by 34875634567** [spring-cloud/spring-cloud-function#996] opened 2023-01-27 17:21 UTC
Hi, I've tried using the 4.x builds with with Spring Boot 3.x and found across a runtime error:

```
c.a.s.l.runtime.api.client.AWSLambda     : Started AWSLambda in 4.117 seconds (process running for 6.077)
No qualifying bean of type 'org.springframework.cloud.function.context.FunctionCatalog' available: org.springframework.beans.factory.NoSuchBeanDefinitionException
org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'org.springframework.cloud.function.context.FunctionCatalog' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:340)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:331)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1148)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.start(FunctionInvoker.java:144)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:79)
	at org.springframework.cloud.function.adapter.aws.FunctionInvoker.<init>(FunctionInvoker.java:83)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
```

This required a couple of dependency version bumps as shown here:
 https://github.com/spring-cloud/spring-cloud-function/compare/main...34875634567:spring-cloud-function:spring-boot-3

Some test code is included to reproduce the error with `docker-compose up` and `docker/test.sh`.

**Comment by olegz** [comment] 2023-03-01 10:39
Please provide a way to reproduce it. FunctionCatalog is the most fundamental component in s-c-function. Without it nothing would work. This would be a drop-everything-blocker issue. I suspect something is wrong with your configuration, but without a way to reproduce it it is impossible to say other than the auto-configuration for s-c-function is not getting picked up.

**Comment by olegz** [comment] 2023-03-08 07:20
Closing due to lack of reproducible followup and additional details from the original reporter

**Closed by olegz** 2023-03-08 07:20 UTC
Labels: invalid

**Comment by solidline** [comment] 2023-05-19 19:50
Ran into the same issue when using spring-boot 3.x and 4.x function in aws. I was able to confirm 3.2.10 works as expected. Using gradle to this is test project used: https://github.com/solidline/spring-cloud-function/commit/bbb303b123090627ccb8f72c169fa09fd4faee0b 

error response in aws:

```json

{
  "errorMessage": "No qualifying bean of type 'org.springframework.cloud.function.context.FunctionCatalog' available",
  "errorType": "org.springframework.beans.factory.NoSuchBeanDefinitionException"
}

```

as of now no known solution.
