### ISSUE TITLE
Spring Cloud Functions GCP : does not implement com.google.cloud.functions.HttpFunction and did not produce the class "org.springframework.cloud.function.adapter.gcp.GcfJarLauncher"

### ISSUE THREAD

**Issue by arundotin** [spring-cloud/spring-cloud-function#665] opened 2021-03-12 13:39 UTC
When i deploy my `jar` file in GCP cloud-functions, i am getting the below exception

```
2021-03-11T17:30:04.835Zarun-function-http Exception in thread "main" java.lang.RuntimeException: Class com.arun.serverless.CloudFunctionMain does not implement com.google.cloud.functions.HttpFunction at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:47) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:252) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:127)
Exception in thread "main" java.lang.RuntimeException: Class com.arun.serverless.CloudFunctionMain does not implement com.google.cloud.functions.HttpFunction at com.google.cloud.functions.invoker.HttpFunctionExecutor.forClass(HttpFunctionExecutor.java:47) at com.google.cloud.functions.invoker.runner.Invoker.startServer(Invoker.java:252) at com.google.cloud.functions.invoker.runner.Invoker.main(Invoker.java:127)
```

This is another error that i get in CLI

```
ERROR: (gcloud.alpha.functions.deploy) OperationError: code=3, message=Build failed: build succeeded but did not produce the class "org.springframework.cloud.function.adapter.gcp.GcfJarLauncher" specified as the function target: Error: class not found: org.springframework.cloud.function.adapter.gcp.GcfJarLauncher; Error ID: d818fd83
```

[This is my source code](https://github.com/arundotin/spring-gcp-serverless)

This is my spring main class

```java
import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class CloudFunctionMain {

    public static void main(String[] args) {
        SpringApplication.run(CloudFunctionMain.class, args);
    }

}
```

This is my function

```java
import java.util.function.Function;

public class ReverseString implements Function<String, String> {

    @Override
    public String apply(String actualString) {
        return "The reversed string is " + new StringBuilder(actualString).reverse().toString();
    }
}
```

This is what my `build.gradle` contains

```
plugins {
    id 'java'
}

group 'com.arun'
//version '1.0'

repositories {
    mavenRepository()
}

dependencies {
    implementation 'org.springframework.cloud:spring-cloud-function-adapter-gcp:3.1.1'
    implementation 'org.springframework.cloud:spring-cloud-starter-function-web:3.1.1'
}
```

It works perfectly fine in my local... But when i deploy in GCP Cloud functions (deploy command give below) it isn't getting started and stopping with the exception that i pasted above

```
gcloud alpha functions deploy arun-function-http \
--entry-point org.springframework.cloud.function.adapter.gcp.GcfJarLauncher \
--runtime java11 \
--trigger-http \
--source build/libs \
--memory 512MB
```

I would like to see it deployed in google-functions without any issue. Need some help here

**Comment by olegz** [comment] 2021-04-09 05:48
@meltsufin can you see if one of you guys can take a look at this?

**Comment by meltsufin** [comment] 2021-04-14 15:40
@arundotin Have you tried running the [sample](https://github.com/spring-cloud/spring-cloud-function/tree/master/spring-cloud-function-samples/function-sample-gcp-http). It looks very similar to your code. Does it work for you? I just tested the sample and it seems to work fine for me.

**Comment by ripper2hl** [comment] 2021-07-10 17:57
You need add `@Component`


```java
import java.util.function.Function;

@Component
public class ReverseString implements Function<String, String> {

    @Override
    public String apply(String actualString) {
        return "The reversed string is " + new StringBuilder(actualString).reverse().toString();
    }
}

```

**Comment by meltsufin** [comment] 2021-11-30 14:45
Since we're unable to reproduce and the OP hasn't followed up on the questions, closing.

**Closed by meltsufin** 2021-11-30 14:45 UTC
Labels: ideal-for-contribution, GCF
