### ISSUE TITLE
The Spring cloud function always return 200 ok

### ISSUE THREAD

**Issue by shan5469** [spring-cloud/spring-cloud-function#1130] opened 2024-04-02 06:27 UTC
Hello,

I'm trying to return a custom Http response using Function<String, ResponseEntity<String>>, but the response status is always 200, and in case of bad request, I receive something like this in the body:

`{
    "headers": {},
    "body": "Processed input: hello",
    "statusCode": "BAD_REQUEST",
    "statusCodeValue": 400
}`

**Comment by olegz** [comment] 2024-04-25 14:27
Can you please provide more context about your question. I honestly can make anything out of it. How do I reproduce it? What is it about?

**Comment by olegz** [comment] 2024-06-11 11:58
I am closing it due to lack of details and follow up from the original reporter.

**Closed by olegz** 2024-06-11 11:58 UTC
Labels: question, waiting-on-feedback
