### ISSUE TITLE
when run 'mvnw clean install' throw exception: missingType(org.springframework.cloud.function.compiler.java.RuntimeJavaCompiler Tests)  Time elapsed: 1.538 sec  <<< FAILURE!

### ISSUE THREAD

**Issue by jthinking** [spring-cloud/spring-cloud-function#187] opened 2018-07-05 16:00 UTC
```
New FunctionCompiler: 2487ms
New FunctionCompiler: 2405ms
New FunctionCompiler: 2394ms
Tests run: 9, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 48.428 sec
Running org.springframework.cloud.function.compiler.ConsumerCompilerTests
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.863 sec
Running org.springframework.cloud.function.compiler.FunctionCompilerTests
Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 4.882 sec
Running org.springframework.cloud.function.compiler.java.RuntimeJavaCompilerTest
s
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 23.888 sec <<< F
AILURE!
missingType(org.springframework.cloud.function.compiler.java.RuntimeJavaCompiler
Tests)  Time elapsed: 1.538 sec  <<< FAILURE!
java.lang.AssertionError
        at org.junit.Assert.fail(Assert.java:86)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at org.junit.Assert.assertTrue(Assert.java:52)
        at org.springframework.cloud.function.compiler.java.RuntimeJavaCompilerT
ests.missingType(RuntimeJavaCompilerTests.java:56)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(Framework
Method.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCal
lable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMe
thod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMet
hod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRun
ner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provide
r.java:252)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4
Provider.java:141)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider
.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.apache.maven.surefire.util.ReflectionUtils.invokeMethodWithArray(
ReflectionUtils.java:189)
        at org.apache.maven.surefire.booter.ProviderFactory$ProviderProxy.invoke
(ProviderFactory.java:165)
        at org.apache.maven.surefire.booter.ProviderFactory.invokeProvider(Provi
derFactory.java:85)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(Fork
edBooter.java:115)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:
75)

Running org.springframework.cloud.function.compiler.proxy.ByteCodeLoadingFunctio
nTests
foo
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 11.509 sec
Running org.springframework.cloud.function.compiler.SupplierCompilerTests
Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 9.691 sec
Running org.springframework.cloud.function.core.FunctionFactoryUtilsTests
Tests run: 4, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.002 sec

Results :

Failed tests:   missingType(org.springframework.cloud.function.compiler.java.Run
timeJavaCompilerTests)

Tests run: 29, Failures: 1, Errors: 0, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Spring Cloud Function Dependencies ................. SUCCESS [  1.974 s]
[INFO] Spring Cloud Function Parent ....................... SUCCESS [03:18 min]
[INFO] Spring Cloud Function Core ......................... SUCCESS [  7.494 s]
[INFO] Spring Cloud Function Compiler ..................... FAILURE [02:16 min]
[INFO] spring-cloud-function-context ...................... SKIPPED
[INFO] Spring Cloud Function Task Support ................. SKIPPED
[INFO] Spring Cloud Function Web Support .................. SKIPPED
[INFO] spring-cloud-starter-starter-function-web .......... SKIPPED
[INFO] function-sample .................................... SKIPPED
[INFO] function-sample-pof ................................ SKIPPED
[INFO] function-sample-pojo ............................... SKIPPED
[INFO] spring-cloud-function-sample-compiler .............. SKIPPED
[INFO] function-sample-task ............................... SKIPPED
[INFO] spring-cloud-function-adapter-parent ............... SKIPPED
[INFO] spring-cloud-function-adapter-aws .................. SKIPPED
[INFO] function-sample-aws ................................ SKIPPED
[INFO] spring-cloud-function-adapter-aws .................. SKIPPED
[INFO] function-sample-azure .............................. SKIPPED
[INFO] Spring Cloud Function Samples ...................... SKIPPED
[INFO] spring-cloud-function-deployer ..................... SKIPPED
[INFO] spring-cloud-function-adapter-openwhisk ............ SKIPPED
[INFO] Spring Cloud Function Docs ......................... SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 06:06 min
[INFO] Finished at: 2018-07-05T23:58:22+08:00
[INFO] Final Memory: 102M/511M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.
12.4:test (default-test) on project spring-cloud-function-compiler: There are te
st failures.
[ERROR]
[ERROR] Please refer to C:\Users\Bochao\Desktop\spring-cloud-function-master\spr
ing-cloud-function-compiler\target\surefire-reports for the individual test resu
lts.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e swit
ch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please rea
d the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureExc
eption
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command

[ERROR]   mvn <goals> -rf :spring-cloud-function-compiler

```

**Comment by olegz** [comment] 2018-07-05 17:44
@jthinking it would help if you could provide more information such as environment, JDK, version of SCF (master or some branch) etc. . .

**Comment by jthinking** [comment] 2018-07-06 05:22
@olegz thanks, and i've fixed it by deleting the test folder of the spring-cloud-function-compiler module. maybe i should use the releases instead of downloaded the master branch code

**Comment by olegz** [comment] 2018-07-06 10:39
I am not sure, but I can't reproduce it with the information provided. 
In any event, as it appears to be working for you and is not reproducible I'll close it for now, but feel free to re-open or re-report if problem persists. make sure you include directives on how to reproduce and other relevant info.

**Closed by olegz** 2018-07-06 10:39 UTC
Labels: waiting-on-feedback

**Comment by quaff** [comment] 2018-08-16 11:16
I have the same problem, oracle jdk 1.8.0_181 on macOS.

**Comment by quaff** [comment] 2018-08-16 11:28
@olegz It's caused by locale, javac reports error message in chinese on my computer, such as  "找不到符号" instead of "cannot find symbol".
