### ISSUE TITLE
Using catalog.getNames return an empty set

### ISSUE THREAD

**Issue by neokeld** [spring-cloud/spring-cloud-function#275] opened 2019-03-13 18:01 UTC
First i want to say a big thanks for spring-cloud-function !

My issue :
When using catalog.getNames, it returns an empty set.

I've defined six functions as classes :
- one as a Supplier<String>
- five as Function (as Function<String, String> or Function<Flux<String>, Flux<String>>)

In my @SpringBootApplication i define :

	public static void main(String[] args) {
		ConfigurableApplicationContext context = 
				SpringApplication.run(FunctionApplication.class, args);
		String[] singletonNames = context.getBeanDefinitionNames();
		for (String singleton : singletonNames) {
			System.out.println(singleton);
		}
		FunctionCatalog catalog = (FunctionCatalog) context.getBean("functionCatalog");
		System.out.println(catalog.getNames(Supplier.class));
		System.out.println(catalog.getNames(Consumer.class));
		System.out.println(catalog.getNames(Function.class));
		System.out.println(catalog.size());
		context.close();
	}

This print :
[listOfAllFunctions]
[]
[]
6

Indeed i have a function whose name is ListOfAllFunctions and a total of 6 functions but catalog.getNames(Function.class) return an empty Set.
Am i using getNames wrongly ?
Thanks a lot.

(i do this because i want to list available Functions in my "Service Core" which calls Functions)

**Comment by olegz** [comment] 2019-03-13 19:04
Strange indeed. I just tried and everything works as expected (see the full code below).
```
@SpringBootApplication
public class Issue275App {

	public static void main(String[] args) {
		ApplicationContext context = SpringApplication.run(Issue275App.class);
		FunctionCatalog catalog = context.getBean(FunctionCatalog.class);
		System.out.println(catalog.getNames(Function.class));
		System.out.println(catalog.getNames(Supplier.class));
		System.out.println(catalog.getNames(Consumer.class));
	}

	@Bean
	public Function<String, String> echo() {
		return v -> v;
	}

	@Bean
	public Function<Flux<Long>, Flux<Long>> foo() {
		return v -> v;
	}

        @Bean
	public Consumer<Flux<String>> consume() {
		return v -> System.out.println(v);
	}
}
```
. . . and output:
```
[foo, consume, echo]
[]
[]
```
You can see that `consume` returned as Function since it is effectively wrapped into Function<Flux<String>, Mono<Void>>`, but that is another discussion. The point is hat all functions that are defined are available in catalog.

In any event, would you be able to provide full sample that reproduces it?

**Comment by neokeld** [comment] 2019-03-14 13:12
Thanks !
Yes you can get it here : https://github.com/neokeld/function-example

**Comment by neokeld** [comment] 2019-03-14 13:51
Ok that was a bad import :
import org.apache.el.lang.FunctionMapperImpl.Function;
instead of
import java.util.function.Function;

There is no bug.
Thanks a lot for your help !

**Comment by olegz** [comment] 2019-03-14 15:07
I guess it is no longer an issue. Closing

**Closed by olegz** 2019-03-14 15:07 UTC
