### ISSUE TITLE
SmartCompositeMessageConverter swallows conversion errors for simple types

### ISSUE THREAD

**Issue by LukeKynaston** [spring-cloud/spring-cloud-function#1168] opened 2024-07-30 10:48 UTC
Actual Behaviour:

When a message is received and the consumer accepts a simple type i.e. a raw Map without generics information, any conversion errors will be swallowed. 

`org.springframework.cloud.function.context.catalog.SimpleFunctionRegistry.FunctionInvocationWrapper#convertInputMessageIfNecessary` will call `SmartCompositeMessageConverter#fromMessage(Message<?> message, Class<?> targetClass)` when no convertionHint is required. This results in errors thrown by any of the converters being swallowed as the Exception is caught, a debug message logged, and null is returned. Once the list of converters is exhausted, null is returned to the caller and the `Message#payload` is passed to the consumer as is (e.g. byte[]), this then results in a `ClassCastException` being raised.

Expected Behaviour:
`SmartCompositeMessageConverter#fromMessage(Message<?> message, Class<?> targetClass)` should propagate the Exception just like  `SmartCompositeMessageConverter#fromMessage(Message<?> message, Class<?> targetClass, @Nullable Object conversionHint)` so that message conversion errors are handled consistently. 

Affects versions: 3.x, 4.x

The issue can be recreated with a simple unit test.

**Comment by tomek82** [comment] 2024-09-10 20:34
This is related to https://github.com/spring-cloud/spring-cloud-function/issues/739 and is an unfortunate choice of default behavior.

In my case I'm using function routing based on a message header and have each function accept a specific record that's deserialized from JSON. If the payload is malformed I want the message to not even touch the function and go to the configured error handler (I'm using Spring Cloud Stream) but instead I'm receiving a Message<byte[]> which gets me ClassCastException as soon as I call getPayload().

**Comment by olegz** [comment] 2024-09-23 16:40
Well, this is a default behavior and the intention is to allow user to receive a raw message by changing function signature (even temporarily), primarily to investigate. This is because conversion errors are usually development-type errors and could be fixed in many different ways including by adding your own MessageConverter to the stack - https://docs.spring.io/spring-cloud-function/reference/spring-cloud-function/programming-model.html#user-defined-message-converters

So what would you propose to change?

**Comment by tomek82** [comment] 2024-10-02 18:38
I think the better thing to do is to let the configured error handler (as in Consumer<ErrorMessage>) process those, which is what happens anyway once the casting exception happens. The main difference is that the user-defined function doesn't get called with incompatible argument type.

**Comment by olegz** [comment] 2024-10-17 13:16
@LukeKynaston Please look at this [commit](https://github.com/spring-cloud/spring-cloud-function/commit/6dee668e3ec20710460b0384a8b6afe53d078633). The issue has been resolved similarly to what you are describing.  You can create a bean that implements `MessageConverterHelper` and implement 
```
default boolean shouldFailIfCantConvert(Message<?> message) {
	return false;
}
```
We provide a default one, but as you can see the `shouldFailIfCantConvert` method return false to preserve the existing behavior, but you can override it, thus making it fail.

Please let me know if that is sufficient or you were looking for something else

**Comment by LukeKynaston** [comment] 2024-11-06 14:37
@olegz, Thanks I think this will resolve our issue :). I'll check with the team before closing this, just to make sure everyone is happy with this solution.

**Comment by olegz** [comment] 2024-12-20 12:36
@LukeKynaston I assume this could be closed?

**Closed** 2024-12-22 12:43 UTC
Labels: bug

**Comment by kelseyh** [comment] 2025-01-10 14:51
Hi @olegz 
I work with Luke. Unfortunately, he's been off due to illness. 
While I think we can make things work with the above commit, I'm not convinced it's the correct approach. `MessageConverter#fromMessage` states `If the converter does not support the specified media type or cannot perform the conversion, it should return null.` 

Given the above contract, I would expect converter implementations to handle exceptions and return null if they wish to be lenient/leave it to another converter to try the conversion. 

In the case above the MessageConverter in question attempts to do the conversion as it "can" perform the conversion, the resulting exception should be surfaced immediately and the error handler called instead of trying the other converters IMO as this may actually lead to unexpected behaviour.
