### ISSUE TITLE
Kotlin compilation error with spring-cloud-function 4.2.0-

### ISSUE THREAD

**Issue by bnasslahsen** [spring-cloud/spring-cloud-function#1218] opened 2024-12-07 14:31 UTC
**Describe the bug**
Kotlin compilation error with spring-cloud-function `4.2.0`

*Versions of the framework:*
- Spring Boot 3.4.0
- Spring Cloud: 2024.0.0
- Kotlin: 1.9.25
- Java: 17

**Sample**
To reproduce:

1. Generate the project from https://start.spring.io/#!type=maven-project&language=kotlin&platformVersion=3.4.0&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=web,cloud-function
2. unzip and compile the project:

```sh
./mvnw compile
```

**Current behavior**
Compilation error:
```
[ERROR] Failed to execute goal org.jetbrains.kotlin:kotlin-maven-plugin:1.9.25:compile (compile) on project springdoc-openapi-starter-common: Compilation failure
[ERROR] /opt/repository/org/springframework/cloud/spring-cloud-function-context/4.2.0/spring-cloud-function-context-4.2.0.jar!/META-INF/spring-cloud-function-context.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 2.1.0, expected version is 1.9.0.
[ERROR] -> [Help 1]
```

**Expected behavior**
No compilation error

Added minimal reproducer project just in case:
[demo3.zip](https://github.com/user-attachments/files/18048743/demo3.zip)

**Comment by olegz** [comment] 2024-12-09 10:22
We do not specify Kotlin version anywhere in s-c-function, so it is pulled transitively. 
Yes I was able to reproduce the issue with your reproducer (thank you) and it appears that something has changed upstream (perhaps in boot) since if you upgrade cloud version to 2024.0.1-SNAPSHOT, everything compiles just fine.

Please let me know, so I can close this issue

**Comment by olegz** [comment] 2024-12-10 07:03
Seems like it is indeed random, so we need to be explicit about it. . .
Thank you @spencergibb for adding it - https://github.com/spring-cloud/spring-cloud-function/commit/0a43fc92d547055af8b07ce591ba9d60550bb377

**Closed by olegz** 2024-12-10 07:03 UTC

**Comment by bnasslahsen** [comment] 2024-12-10 08:05
Wonderful, thanks @olegz and @spencergibb! 
Looking forward to 4.2.1—maybe it’ll arrive just in time for Christmas!

**Comment by johnnymo87** [comment] 2025-01-14 17:40
Hi @olegz is there a snapshot available anywhere that contains this fix? I'm unable to upgrade to Spring Boot 3.4.x until I can get access to this fix. 🙏

**Comment by 10marianosikJoz** [comment] 2025-01-21 15:41
> Hi [@olegz](https://github.com/olegz) is there a snapshot available anywhere that contains this fix? I'm unable to upgrade to Spring Boot 3.4.x until I can get access to this fix. 🙏

I have same issue.

**Comment by StefanLobbenmeierObjego** [comment] 2025-01-28 15:20
issue seems to be introduced from 4.1.4 onwards, here is what I tested

- spring-cloud-function-context-4.1.3.jar ✅ 
- spring-cloud-function-context-4.1.4.jar ❌ 
- spring-cloud-function-context-4.1.5.jar ❌ 
- spring-cloud-function-context-4.2.0.jar ❌

**Comment by StefanLobbenmeierObjego** [comment] 2025-01-28 17:27
4.2.1 works on my machine, edited my comment for clarification.

There is no version of org.springframework.cloud:spring-cloud-dependencies yet that includes that release so I had to specify the version manually

**Comment by spencergibb** [comment] 2025-01-28 17:29
> There is no version of org.springframework.cloud:spring-cloud-dependencies yet that includes that release so I had to specify the version manually

That is correct, it was specifically released outside the release train, in part, for this issue.
