### ISSUE TITLE
SpringBootApiGatewayRequestHandler always returning statusCode 200

### ISSUE THREAD

**Issue by gaston-freire** [spring-cloud/spring-cloud-function#206] opened 2018-09-11 14:15 UTC
Hi everyone.

I am using 1.0.1.RELEASE version and I have found and issue when trying to report a validation error through SpringBootApiGatewayRequestHandler.

My function returns a GenericMessage containing a payload (a simple POJO with error details) and the following header:
`Map<String, Object> headers = Collections.singletonMap("statusCode", 400);`

The convertOutput method in SpringBootApiGatewayRequestHandler is defaulting to 200 when looking for the "statusCode" header in the response message.

 	@Override
	protected APIGatewayProxyResponseEvent convertOutput(Object output) {
		if (functionReturnsMessage(output)) {
			Message<?> message = (Message<?>) output;
			return new APIGatewayProxyResponseEvent().withStatusCode(
					(Integer) message.getHeaders().getOrDefault("statusCode", 200))
					.withHeaders(toResponseHeaders(message.getHeaders()))
					.withBody(serializeBody(message.getPayload()));
		}
		else {
			return new APIGatewayProxyResponseEvent().withStatusCode(200)
					.withBody(serializeBody(output));
		}
	}

I tracked the problem down to the FluxReturnValueHandler class, where the headers from the message are read using HeaderUtils.fromMessage method. This method converts to lower case all the header names. Then, the convertOutput method cannot find the mixed-case "statusCode" header.

This should be fixed by changing only this line in SpringBootApiGatewayRequestHandler

`(Integer) message.getHeaders().getOrDefault("statuscode", 200))`

but I don't know if this has any undesired side effects.
Is there a better way of fixing this? Am I missing something?

Thanks in advance for your help.

Regards.

**Comment by olegz** [comment] 2018-09-11 19:36
@gastonfreireamoedo I know it's not the ideal answer nor it is the final answer from our end, but can you please try the same with 2.0.0.BUILD-SNAPSHOT version of Spring Cloud Function? At the very least it would help us to debug the issue.

**Comment by dsyer** [comment] 2018-09-12 12:09
I doubt it has changed - we didn't change the adapter did we? The issue is that HTTP headers are case insensitive but `Message` headers are not. The proposed fix looks fine to me.

**Comment by olegz** [comment] 2020-07-29 19:05
Given that we effectively deprecated request handlers in favor of a single and universal FunctionInvoker - https://docs.spring.io/spring-cloud-function/docs/3.0.8.RELEASE/reference/html/aws.html#_getting_started I am now wondering if there is still work that needs to be done here?

**Comment by olegz** [comment] 2021-07-16 14:02
I'll close it as `SpringBootApiGatewayRequestHandler` has been deprecated in favor of FunctionInvoker. Please feel free to raise a new issue

**Closed by olegz** 2021-07-16 14:02 UTC
Labels: enhancement, waiting-on-feedback
