### ISSUE TITLE
Object Mapping removing fields with underscore as first character (example "_id")

### ISSUE THREAD

**Issue by dmarley** [spring-cloud/spring-cloud-function#900] opened 2022-07-19 23:13 UTC
**Describe the bug**
Within the handler and function we specify the input and output Bean types.  If the beans have a field which has a underscore (example _id) that field is not set in the bean nor the output json response back to the client.   If I just use <String, String> and do my own objectMapper.readValue(json, <MYOBJECT>) it works as expected.

**Comment by olegz** [comment] 2022-07-26 10:21
We do not remove any fields and delegate to underlying API. I am not sure what are you doing in your ObjectMapper with regard to configurations, but you can easily implement your own custom message converter that will behave as you expect - https://docs.spring.io/spring-cloud-function/docs/current/reference/html/spring-cloud-function.html#user-defined-message-converters.

Basically i don't see anything here that we need to do. Please let me know if you think otherwise.

**Comment by olegz** [comment] 2022-08-03 16:10
anything?

**Comment by olegz** [comment] 2022-08-04 11:12
I am going to close it due to lack of follow up from the original reporter. If you feel there is still an issue please provide more details and a small application (push it somewhere in github or attach a zip) that reproduces the issue so we can analize

**Closed by olegz** 2022-08-04 11:12 UTC
Labels: waiting-on-feedback
