### ISSUE TITLE
A Function with a Map as input receives a Map with non-primitive values converted to String

### ISSUE THREAD

**Issue by blake-bauman** [spring-cloud/spring-cloud-function#768] opened 2021-11-16 00:45 UTC
**Description**

If you have a function which receives a Map as input (i.e. `Function<Map<String, Object>, Foo>`, and a Map is passed as input which contains non-primitive values (i.e. `Date`), the values in the Map get converted to Strings.

This started happening as of 3.1.4.  Reverting to 3.1.3 resolves this issue.

The problem seems to be in [FunctionInvocationWrapper.convertInputIfNecessary()](https://github.com/spring-cloud/spring-cloud-function/blob/v3.1.4/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L987).  In 3.1.4 an additional condition was added with `input instanceof Map` in the call to `this.convertNonMessageInputIfNecessary` which makes `maybeJson == true` instead of `false` as it is in 3.1.3.  This causes the Map to be serialized as Json and then converted back into a Map which loses all type information of the contents.  So, something like a `Date` becomes a `String` representation of a Date.  (This also adds unnecessary overhead given that the source and target types are the same.)

In 3.1.3, `maybeJson` is `false` in this scenario and the `MapToMapConverter` gets used instead, which simply copies the key/value pairs instead of serializing/deserializing.

**Sample**

To reproduce:

1. Create a `@Bean` of type `Function<Map<String, Object>, String>`.
2. Use `FunctionCatalog.lookup()` to retrieve this function.
3. Call `apply()` on the function with a Map containing a `Date` as the value.
4. Set a breakpoint inside the function to see that the Map now contains a `String` instead of a `Date`.

**Comment by blake-bauman** [comment] 2021-11-19 10:02
Is this something that can be included in the December release?  This is impacting any jobs which use MongoDB's `Document` object as input since it implements `Map`.

**Comment by olegz** [comment] 2021-11-19 10:04
@blake-bauman thanks for pointing out. Yes I just scheduled it!

**Comment by blake-bauman** [comment] 2021-11-19 10:05
Sounds great.  Thanks for the quick response!

**Comment by olegz** [comment] 2021-11-30 14:25
It may have been fixed already as part of some other fix, but i can not longer reproduce it. In fact I am pushing few tests to validate it before resolving it.
In other words try it with 3.1.5.

**Comment by blake-bauman** [comment] 2021-11-30 18:49
I was able to reproduce with 3.1.5.  The path is the same.

https://github.com/spring-cloud/spring-cloud-function/blob/v3.1.5/spring-cloud-function-context/src/main/java/org/springframework/cloud/function/context/catalog/SimpleFunctionRegistry.java#L1034

I looked at the tests, and I think the issue with the tests is that it's not using any non-primitive values as input (not counting container types).  If you had a Function like `Function<Map<String, Date>, Date>` and passed in a `Map.of("foo", new Date())` as input, returning the value as output, it should recreate the issue.  Jackson will serialize the Date into a String and then deserialize as a String.

**Comment by blake-bauman** [comment] 2021-11-30 19:31
It seems that it does work if the input is wrapped in a Message, like `Function<Message<Map<String, Date>>, Date>`.  this seems to get sent down a different path which leaves the Map intact.

**Comment by olegz** [comment] 2021-11-30 19:33
Yes, it does go a different path since with Message it uses `MessageConverters` otherwise it relies on standard Spring's `ConversionService`. But that gives me a path to fix it

**Comment by olegz** [comment] 2021-11-30 21:11
@blake-bauman actually I still can't reproduce it. I just pushed a change to a test that is based on your suggestion and everything work as expected. So I am a bit puzzled . . . Would be nice to have a concrete way to reproduce it. Perhaps you can make a PR of a failing test?

**Comment by blake-bauman** [comment] 2021-11-30 22:46
That's my bad.  I mistyped.  I apologize.  The `@Bean` definition itself needs to be `Function<Map<String, Object>, Object>` while passing in a `Map.of("foo", new Date())` as the input arg, returning map.get("foo") from the Function.

**Comment by blake-bauman** [comment] 2021-11-30 22:48
I'm working on creating a standalone sample outside of my project.  (I have to get approval from my company first to post it publicly.)

**Comment by olegz** [comment] 2021-12-01 07:51
Ok, I am resolving it as I believe there are no issue. I just modified my test as you suggested and now I see that both Message and non-Message cases fail.
```
@Bean
public Function<Map<String, Object>, String> echoToString() {
	return data -> {
		for (Entry<String, Object> dataEntry : data.entrySet()) {
			assertThat(dataEntry.getValue()).isInstanceOf(Date.class); // would fail if value would not be converted to Person
		}
		return data.toString();
	};
}

@Bean
public Function<Message<Map<String, Object>>, String> echoMessageToString() {
	return data -> {
		for (Entry<String, Object> dataEntry : data.getPayload().entrySet()) {
			assertThat(dataEntry.getValue()).isInstanceOf(Date.class); // would fail if value would not be converted to Person
		}
		return data.toString();
	};
}
```
. .  and rightfully so

How would we know your intention if you declare that value is an Object?  In fact that is not us who is doing it, rather Jackson `mapper.readValue(json, Object.class)`

You may still submit an example and we can review and hopefully address it as separate issue. .  more like a feature. Although I can't see how we can give you an instance of specific object without knowing its type and passing it to jackson/gson

**Closed by olegz** 2021-12-01 07:51 UTC
Labels: bug, 3.1.x backport

**Comment by blake-bauman** [comment] 2021-12-01 09:38
I would agree that there's no way Jackson could know the type info.  However, the issue that I was reporting was that in 3.1.3, the Map never was sent to Jackson in the first place if the Function was accepting a Map as input.

>  In 3.1.3, `maybeJson` is false in this scenario and the `MapToMapConverter` gets used instead, which simply copies the key/value pairs instead of serializing/deserializing.

In this case, the input is a Map and the Function accepts a Map with the same K/V types.  So, no Jackson conversion should take place.  MapToMapConverter was handling this as expected in 3.1.3, and keeping the data and types intact.

Starting in 3.1.4, the Map gets sent to Jackson instead of the MapToMapConverter which loses the type information.

I'll get the sample in soon.

**Comment by olegz** [comment] 2021-12-01 09:40
Sure and please raise a new issue for that. The best thing would be a failing test case as a pool request, but i'll take anything ;)
