### ISSUE TITLE
Hoxton.SR9 + functions + reactive stream compatibility issue

### ISSUE THREAD

**Issue by tdanylchuk** [spring-cloud/spring-cloud-function#608] opened 2020-11-17 20:07 UTC
I have a reactive application with spring cloud stream kafka consumer configured.
My consumer bean looks like:
```
public class MyConsumer implements Consumer<Flux<MyObject>> {
    @Override
    public void accept(Flux<MyObject> rewardsFlux) {
        rewardsFlux.doOnNext(event -> log.debug("Consumed reward event - {}.", event))
                .subscribe();
    }
}
```

and its configs (plus destination and kafka broker config)
```
spring:
    cloud.stream:
        bindings:
            my-binding:
                group: ${spring.application.name}
                content-type: application/json
        function:
            bindings:
                myConsumer-in-0: my-binding
            definition: myConsumer
```

So this setup worked alright on version `Hoxton.SR8` but stop working in the right way after bumping dependencies to the latest versions. The problem is that my object contains null fields after de-serialization. I dug a bit deeper and found that this commit https://github.com/spring-cloud/spring-cloud-function/commit/222aac77ccbcc9dd9018101f131fdf93a0f466f0 is actually breaking expected behavior since its checking raw type with actual type 
rawType = `MyCustomObject`
type = `Flux<MyCustomObject>`
and since they are different it puts a deserialization hint (as a view) to the converter.

Please note that if **spring-cloud-function-context** dependency would be downgraded  3.0.11.RELEASE -> 3.0.10.RELEASE. everything will work as expected.

**Comment by olegz** [comment] 2020-11-20 10:30
So indeed there was regression with 3.0.x branch. Thanks or reporting. I fixed it there. Thankfully on master there is no regression given recent refactorings in  FunctionRegistry implementation.

**Comment by tdanylchuk** [comment] 2020-11-20 14:56
Yeah, I was looking at master also, but for some reason, my Idea just could not load this project, it just freezes ;D

Anyways thank you for the fix!

**Comment by tdanylchuk** [comment] 2021-02-05 18:06
@olegz seems like fix does not work on functions in combination with ```spring-messaging``` module, since provided fix works okay if the passed object is not an instance of ```Message``` , in case of messaging module it will be ```GenericMessage``` and will fail on deserialization
Interesting fact, that this will work if a raw object is parametrized also like ```MyCustomObject<SomeGeneric>```, so logic will pass this if
![image](https://user-images.githubusercontent.com/3741358/107071641-04aa2b00-67b3-11eb-97c9-03a91d33776b.png)

**Comment by olegz** [comment] 2021-02-05 18:10
I see your point. We're planning next service release by Feb 11, so i'll add a test and we should have it fixed by then

**Comment by tdanylchuk** [comment] 2021-02-05 18:33
Thank you for that fast response, look forward for the fix!

**Comment by olegz** [comment] 2021-02-08 14:34
@tdanylchuk I am a bit confused. 
I just added the following test
```
@Test
public void testGH_608_Message() {
		ApplicationContext context = new SpringApplicationBuilder(SampleFunctionConfiguration.class)
				.run("--logging.level.org.springframework.cloud.function=DEBUG",
						"--spring.main.lazy-initialization=true");
		FunctionCatalog catalog = context.getBean(FunctionCatalog.class);

		Consumer<Flux<Message<String>>> consumer = catalog.lookup("reactivePojoConsumer");
		consumer.accept(Flux.just(new GenericMessage<String>("{\"name\":\"Ricky\"}")));
		SampleFunctionConfiguration config = context.getBean(SampleFunctionConfiguration.class);
		assertThat(((Person) config.consumerInputRef.get()).getName()).isEqualTo("Ricky");
}
```
As you can see I am passing an instance of  `Message` and it passes on both versions of s-c-function. (3.0.x and master).

Also, the code snippet you are referring to will only execute if payload is a Collection or an array. . .

In any event, I can't seem to reproduce it, so perhaps you can provide a failing test case that reproduces the issue

**Comment by tdanylchuk** [comment] 2021-02-08 17:38
sure, let me debug a bit ;D

**Comment by tdanylchuk** [comment] 2021-02-08 17:55
can you please commit your changes to some branch?

**Comment by tdanylchuk** [comment] 2021-02-08 18:10
So I was debugging ```3.0.12.RELEASE``` version (which is different from 3.0.x)
and my case (guess will be same as with urs test) is hitting 
![image](https://user-images.githubusercontent.com/3741358/107262775-f6584b00-6a0e-11eb-8542-3231788c1cbc.png)

**Comment by olegz** [comment] 2021-02-08 18:18
Ok, so my question is have you tried with 3.0.x? It may have already been addressed indirectly.
Also, do you have a test case that i can use to reproduce the issue? This way i could play with several versions and see what's going on.
We're going to release 3.0.13 in two days, so I want to make sure it is addressed.

**Comment by tdanylchuk** [comment] 2021-02-08 18:43
the test case is already at the very top of the ticket, the problem that this case should include `spring-messaging` module to have `pure` test  

Locally (I've built `context` module and included in my app) it works well! So I guess still worth adding the test you've sent above to the project, just to be safe next time=)

Looking forward for `3.0.13` version =)

**Comment by tdanylchuk** [comment] 2021-03-15 15:49
Hello @olegz , seems like latest 3.0.13 version works good with the cases I described above, however, I believe this version introduced a regression with another case I had working on 3.0.12.

So accepted object in function should be ```Flux<MyObject<MyGenericType>>``` and it leads to converting object without the hint, and hence object inside is deserializing into the plain map instead of the generic type object.
![image](https://user-images.githubusercontent.com/3741358/111181482-6ca71a80-8584-11eb-91df-735a16926586.png)

**Comment by olegz** [comment] 2021-04-09 06:54
@tdanylchuk trying to close the loop on this. . .
So if I understand correctly the issue you have is with the type of function that looks like this

```
public Function<Flux<MyObject<MyGenericType>>, SomethingElse> func() {
. . .
}
```

Is that correct?

**Comment by snussbaumer** [comment] 2021-04-09 07:14
Could this be related to the problem I have in [this SO question](https://stackoverflow.com/questions/66990612/how-to-get-the-message-headers-in-a-consumer/67005103?noredirect=1#comment118440171_67005103
) ? 

With Spring Cloud Stream new function based model I see a different behaviour when consuming Message<MyDto> versus MyDto directly. I should get exactly the same deserialization of the payload (right ?) but it's not the case, at ligne 828 of the screen capture of tdanylchuk above I see that convertWithHint is set to true when consuming MyMessage<MyDto> because rawType.equals(type) is false (rawType = MyDto, type = Message<MyDto>). This is not the case when consuming MyDto directly because rawTYpe.equals(type) is true.

(i'm on boot 2.3.8 + cloud Hoxton.SR10)

**Comment by olegz** [comment] 2021-04-09 07:18
Perhaps. . . I guess the best way would be if you can create a small (bare minimum) project that reproduces the issue and push it to GH so e can take a look. You think that's possible?

**Comment by snussbaumer** [comment] 2021-04-09 08:21
I have a repro here : https://github.com/snussbaumer/Gh608/blob/main/src/test/java/com/example/gh608/Gh608ApplicationTests.java

When you run the test it will print 
```
Consumer<Message<Foo>> : Bar [message=null]
```

you can then comment the `Consumer<Message<Foo>> input() {` Bean and uncomment `Consumer<Foo> input() {` below and the test will print : 
```
Consumer<Foo> : Bar [message=hello world]
```

This demonstrates that deserialization is different when you are consuming Message<Foo> instead of Foo directly. Notice that you have to define an objectMapper with DEFAULT_VIEW_INCLUSION to false to see the difference (but at least you see the difference). In my application this is the case and I'm not sure I can change this easily without breaking things elsewhere. 

This happens on boot 2.3.9 + hoxton.SR10 but not with boot 2.4.4 + cloud 2020.0.2

**Comment by olegz** [comment] 2021-04-09 10:28
@snussbaumer As always, thank you very much for providing simple reproducible sample. That is by far the best and the quickest way to get our attention.
The fix is in, the build is running and snapshots `3.0.14-BUILD-SNAPSHOT` will be available in 15-20 min

**Closed by olegz** 2021-04-09 10:28 UTC
Labels: bug, waiting-on-feedback

**Comment by snussbaumer** [comment] 2021-04-09 12:51
thanks, great news :) 

I tried with 3.0.14-BUILD-SNAPSHOT and can confirm it solves my problem in the repro sample but also in my real application.

**Comment by tdanylchuk** [comment] 2021-04-09 16:50
@olegz I believe it's not fully fixed, I've created PR with test which reproduces issue I mentioned above - https://github.com/spring-cloud/spring-cloud-function/pull/683

**Comment by olegz** [comment] 2021-04-10 05:59
Good catch @tdanylchuk. Just merged your PR and pushed the fix, so should be fine now.

P.S. My brother's name Taras ;)

**Comment by olegz** [comment] 2021-04-10 06:11
Also, merged your test to master, just to be sure

**Comment by tdanylchuk** [comment] 2021-04-10 15:24
Thank you!

Sorry for not providing fix within PR, although I thought it would be easy to fix this particular case, that part of the logic has tons of corner cases - didn't want to mess around =)

Looking forward to try the new release!
